"""Generate maintained R/Python API migration tables."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

TABLES = {
'lme4': [
('Random intercept', 'lmer(y ~ x + (1|g), data=d)', 'lmer("y ~ x + (1|g)", d)'),
('Random slope', 'lmer(y ~ x + (x|g), data=d)', 'lmer("y ~ x + (x|g)", d)'),
('Independent slopes', 'lmer(y ~ x + (x||g), data=d)', 'lmer("y ~ x + (x||g)", d)'),
('Crossed intercepts', 'lmer(y ~ x + (1|g)+(1|h), data=d)', 'lmer("y ~ x + (1|g)+(1|h)", d)'),
('Nested intercepts', 'lmer(y ~ x + (1|g/h), data=d)', 'lmer("y ~ x + (1|g/h)", d)'),
('Slope without intercept', 'lmer(y ~ x + (0+x|g), data=d)', 'lmer("y ~ x + (0+x|g)", d)'),
('REML', 'lmer(f, data=d, REML=TRUE)', 'lmer(f, d, reml=True)'),
('ML', 'lmer(f, data=d, REML=FALSE)', 'lmer(f, d, reml=False)'),
('Precision weights', 'lmer(f, data=d, weights=w)', 'lmer(f, d, weights="w")'),
('Offset argument', 'lmer(f, data=d, offset=o)', 'lmer(f, d, offset="o")'),
('Formula offset', 'lmer(y ~ x+offset(o)+(1|g), data=d)', 'lmer("y ~ x+offset(o)+(1|g)", d)'),
('Fixed effects', 'fixef(m)', 'm.fixef()'), ('Conditional modes', 'ranef(m)', 'm.ranef()'),
('Conditional variance', 'ranef(m, condVar=TRUE)', 'm.ranef(cond_var=True)'),
('Variance components', 'VarCorr(m)', 'm.VarCorr()'), ('Fixed covariance', 'vcov(m)', 'm.vcov()'),
('Log likelihood', 'logLik(m)', 'm.logLik()'), ('AIC', 'AIC(m)', 'm.AIC()'), ('BIC', 'BIC(m)', 'm.BIC()'),
('Fit criterion', 'deviance(m)', 'm.deviance()'), ('Fitted values', 'fitted(m)', 'm.fitted()'),
('Residuals', 'residuals(m)', 'm.residuals()'), ('Prediction', 'predict(m, newdata=nd)', 'm.predict(newdata=nd)'),
('Population prediction', 'predict(m, newdata=nd, re.form=NA)', 'm.predict(newdata=nd, re_form="NA")'),
('New groups', 'predict(m,newdata=nd,allow.new.levels=TRUE)', 'm.predict(newdata=nd,allow_new_levels=True)'),
('Singularity', 'isSingular(m)', 'm.is_singular()'), ('Satterthwaite summary', 'summary(m)', 'm.summary()'),
('Likelihood comparison', 'anova(m0,m1)', 'anova(m0,m1)'),
('Binomial logit', 'glmer(f,data=d,family=binomial("logit"),nAGQ=1)', 'glmer(f,d,family="binomial",link="logit")'),
('Binomial probit', 'glmer(f,data=d,family=binomial("probit"),nAGQ=1)', 'glmer(f,d,link="probit")'),
('Binomial cloglog', 'glmer(f,data=d,family=binomial("cloglog"),nAGQ=1)', 'glmer(f,d,link="cloglog")'),
('Binomial counts', 'glmer(cbind(s,f)~x+(1|g),data=d,family=binomial)', 'glmer("cbind(s,f)~x+(1|g)",d)'),
('Poisson', 'glmer(f,data=d,family=poisson,nAGQ=1)', 'glmer(f,d,family="poisson")'),
],
'emmeans': [
('Marginal means','emmeans(m,"a")','emmeans(m,"a")'),
('Two factors','emmeans(m,c("a","b"))','emmeans(m,["a","b"])'),
('Conditioning','emmeans(m,"a",by="b")','emmeans(m,"a",by="b")'),
('Formula conditioning','emmeans(m,~a|b)','emmeans(m,"~a|b")'),
('At a numeric value','emmeans(m,"a",at=list(x=2))','emmeans(m,"a",at={"x":[2]})'),
('At several values','emmeans(m,"x",at=list(x=c(0,1,2)))','emmeans(m,"x",at={"x":[0,1,2]})'),
('Equal weights','emmeans(m,"a",weights="equal")','emmeans(m,"a",weights="equal")'),
('Proportional weights','emmeans(m,"a",weights="proportional")','emmeans(m,"a",weights="proportional")'),
('Cell weights','emmeans(m,"a",weights="cells")','emmeans(m,"a",weights="cells")'),
('Outer weights','emmeans(m,"a",weights="outer")','emmeans(m,"a",weights="outer")'),
('Flat weights','emmeans(m,"a",weights="flat")','emmeans(m,"a",weights="flat")'),
('Pairwise','pairs(e)','pairs(e)'), ('Reverse pairs','pairs(e,reverse=TRUE)','pairs(e,reverse=True)'),
('Pairwise contrast','contrast(e,"pairwise")','contrast(e,"pairwise")'),
('Control contrasts','contrast(e,"trt.vs.ctrl",ref=1,adjust="bonferroni")','contrast(e,"trt.vs.ctrl",ref=1,adjust="bonferroni")'),
('Consecutive contrasts','contrast(e,"consec")','contrast(e,"consec")'),
('Polynomial contrasts','contrast(e,"poly")','contrast(e,"poly")'),
('Custom contrasts','contrast(e,list(diff=c(1,-1,0)))','contrast(e,{"diff":[1,-1,0]})'),
('Tukey adjustment','pairs(e,adjust="tukey")','pairs(e,adjust="tukey")'),
('Bonferroni','pairs(e,adjust="bonferroni")','pairs(e,adjust="bonferroni")'),
('Holm','pairs(e,adjust="holm")','pairs(e,adjust="holm")'),
('Sidak','pairs(e,adjust="sidak")','pairs(e,adjust="sidak")'),
('No adjustment','pairs(e,adjust="none")','pairs(e,adjust="none")'),
('FDR','pairs(e,adjust="fdr")','pairs(e,adjust="fdr")'),
('Response scale','summary(e,type="response")','e.summary(type="response")'),
('Regrid','regrid(e,transform="response")','regrid(e,transform="response")'),
('KR degrees of freedom','emmeans(m,"a",lmer.df="kenward-roger")','emmeans(m,"a",lmer_df="kenward-roger")'),
('Satterthwaite','emmeans(m,"a",lmer.df="satterthwaite")','emmeans(m,"a",lmer_df="satterthwaite")'),
('Asymptotic','emmeans(m,"a",lmer.df="asymptotic")','emmeans(m,"a",lmer_df="asymptotic")'),
('Trends','emtrends(m,"a",var="x")','emtrends(m,"a",var="x")'),
('Joint tests','joint_tests(m)','joint_tests(m)'),
('Confidence limits','confint(e,level=.90)','e.confint(level=.90)'),
('Tests and intervals','summary(e,infer=c(TRUE,TRUE))','e.summary(infer=(True,True))'),
],
'car': [
('OLS Type II','Anova(m,type=2)','Anova(m,type=2)'),
('OLS Type III','Anova(m,type=3)','Anova(m,type=3)'),
('Type labels','Anova(m,type="II")','Anova(m,type="II")'),
('OLS F','Anova(m,type=2,test.statistic="F")','Anova(m,type=2,test_statistic="F")'),
('GLM LR II','Anova(m,type=2,test.statistic="LR")','Anova(m,type=2,test_statistic="LR")'),
('GLM LR III','Anova(m,type=3,test.statistic="LR")','Anova(m,type=3,test_statistic="LR")'),
('GLM Wald II','Anova(m,type=2,test.statistic="Wald")','Anova(m,type=2,test_statistic="Wald")'),
('GLM Wald III','Anova(m,type=3,test.statistic="Wald")','Anova(m,type=3,test_statistic="Wald")'),
('GLM F II','Anova(m,type=2,test.statistic="F")','Anova(m,type=2,test_statistic="F")'),
('GLM F III','Anova(m,type=3,test.statistic="F")','Anova(m,type=3,test_statistic="F")'),
('Mixed Wald II','Anova(m,type=2,test.statistic="Chisq")','Anova(m,type=2,test_statistic="Chisq")'),
('Mixed Wald III','Anova(m,type=3,test.statistic="Chisq")','Anova(m,type=3,test_statistic="Chisq")'),
('Mixed KR II','Anova(m,type=2,test.statistic="F")','Anova(m,type=2,test_statistic="F")'),
('Mixed KR III','Anova(m,type=3,test.statistic="F")','Anova(m,type=3,test_statistic="F")'),
('GLMM Wald II','Anova(gm,type=2)','Anova(gm,type=2)'),
('GLMM Wald III','Anova(gm,type=3)','Anova(gm,type=3)'),
('Satterthwaite I','anova(m,type=1,ddf="Satterthwaite")','anova(m,type=1,ddf="satterthwaite")'),
('Satterthwaite II','anova(m,type=2,ddf="Satterthwaite")','anova(m,type=2,ddf="satterthwaite")'),
('Satterthwaite III','anova(m,type=3,ddf="Satterthwaite")','anova(m,type=3,ddf="satterthwaite")'),
('KR I','anova(m,type=1,ddf="Kenward-Roger")','anova(m,type=1,ddf="kenward-roger")'),
('KR II','anova(m,type=2,ddf="Kenward-Roger")','anova(m,type=2,ddf="kenward-roger")'),
('KR III','anova(m,type=3,ddf="Kenward-Roger")','anova(m,type=3,ddf="kenward-roger")'),
('Default lmerTest III','anova(m)','anova(m)'),
('ML comparison','anova(m0,m1)','anova(m0,m1)'),
('Disable refitting','anova(m0,m1,refit=FALSE)','anova(m0,m1,refit=False)'),
('Sum-coded mixed model','lmer(y~a*b+(1|g),d,contrasts=list(a=contr.sum,b=contr.sum))','lmer("y~a*b+(1|g)",d,contrasts="sum")'),
('Treatment-coded model','lmer(y~a*b+(1|g),d)','lmer("y~a*b+(1|g)",d,contrasts="treatment")'),
('Statsmodels formula OLS','lm(y~a*b,data=d)','smf.ols("y ~ C(a, Sum)*C(b, Sum)",d).fit()'),
('Statsmodels Poisson','glm(y~a,data=d,family=poisson)','smf.glm("y~a",d,family=sm.families.Poisson()).fit()'),
('Statsmodels binomial','glm(y~a,data=d,family=binomial)','smf.glm("y~a",d,family=sm.families.Binomial()).fit()'),
('GLM Pearson dispersion','Anova(m,test.statistic="F",error.estimate="pearson")','Anova(m,test_statistic="F",error_estimate="pearson")'),
],
'nlme': [
('Independent GLS','gls(y~x,data=d)','gls("y~x",d)'),
('REML','gls(y~x,data=d,method="REML")','gls("y~x",d,method="REML")'),
('ML','gls(y~x,data=d,method="ML")','gls("y~x",d,method="ML")'),
('AR1','gls(f,d,correlation=corAR1(form=~t|g))','gls(f,d,correlation=corAR1(form="~t|g"))'),
('AR1 start','corAR1(value=.3,form=~t|g)','corAR1(value=.3,form="~t|g")'),
('Fixed AR1','corAR1(value=.3,form=~t|g,fixed=TRUE)','corAR1(value=.3,form="~t|g",fixed=True)'),
('Compound symmetry','gls(f,d,correlation=corCompSymm(form=~1|g))','gls(f,d,correlation=corCompSymm(form="~1|g"))'),
('Compound symmetry start','corCompSymm(value=.2,form=~1|g)','corCompSymm(value=.2,form="~1|g")'),
('Unstructured','gls(f,d,correlation=corSymm(form=~t|g))','gls(f,d,correlation=corSymm(form="~t|g"))'),
('ARMA11','corARMA(p=1,q=1,form=~t|g)','corARMA(p=1,q=1,form="~t|g")'),
('AR2','corARMA(p=2,q=0,form=~t|g)','corARMA(p=2,q=0,form="~t|g")'),
('MA1','corARMA(p=0,q=1,form=~t|g)','corARMA(p=0,q=1,form="~t|g")'),
('Group variance','gls(f,d,weights=varIdent(form=~1|a))','gls(f,d,weights=varIdent(form="~1|a"))'),
('Variance ratios','varIdent(value=c(b=2),form=~1|a)','varIdent(value={"b":2},form="~1|a")'),
('Power variance','gls(f,d,weights=varPower(form=~v))','gls(f,d,weights=varPower(form="~v"))'),
('Fitted power variance','varPower(form=~fitted(.))','varPower(form="~fitted(.)")'),
('Exponential variance','gls(f,d,weights=varExp(form=~v))','gls(f,d,weights=varExp(form="~v"))'),
('Fitted exponential variance','varExp(form=~fitted(.))','varExp(form="~fitted(.)")'),
('Combined covariance','gls(f,d,correlation=corAR1(form=~t|g),weights=varIdent(form=~1|a))','gls(f,d,correlation=corAR1(form="~t|g"),weights=varIdent(form="~1|a"))'),
('Coefficients','coef(m)','m.coef()'), ('Covariance','vcov(m)','m.vcov()'),
('Likelihood','logLik(m)','m.logLik()'), ('AIC','AIC(m)','m.AIC()'), ('BIC','BIC(m)','m.BIC()'),
('Summary','summary(m)','m.summary()'), ('Sequential ANOVA','anova(m,type="sequential")','m.anova(type="sequential")'),
('Marginal ANOVA','anova(m,type="marginal")','m.anova(type="marginal")'),
('Intervals','intervals(m)','m.intervals()'), ('Coefficients intervals','intervals(m,which="coef")','m.intervals(which="coef")'),
('Predict','predict(m,newdata=nd)','m.predict(newdata=nd)'),
('Residuals','resid(m,type="normalized")','m.residuals(type="normalized")'),
('Fitted','fitted(m)','m.fitted()'),
]}

for module, examples in TABLES.items():
    lines = [f'# {module} migration', '',
             'These examples assume an existing data frame `d` and fitted models. Import the',
             'named functions from `rparity`. For statsmodels examples, import',
             '`statsmodels.api as sm` and `statsmodels.formula.api as smf`.', '',
             'Consult the validation coverage for supported options and known numerical differences.', '']
    if module == 'car':
        lines += ['Type III tests depend on contrast coding. **Use sum contrasts** when testing',
                  'overall main effects in interaction models. This also applies to statsmodels:',
                  'use `C(a, Sum)` in the fitted formula.', '']
    if module == 'emmeans':
        lines += ['Control contrasts require an explicit supported adjustment. The R `dunnettx`',
                  'default is unavailable; Python defaults to `none`.', '']
    if module == 'lme4':
        lines += ['Population prediction uses `re_form="NA"`; `re_form=None` includes conditional',
                  'random effects. `deviance()` for Gaussian models returns the fitted ML/REML',
                  'criterion, consistent with the selected estimation method.', '']
    lines += ['| Use | R | Python |','| --- | --- | --- |']
    for label, r, py in examples:
        lines.append(f'| {label} | `{r.replace(chr(124), chr(92)+chr(124))}` | `{py.replace(chr(124),chr(92)+chr(124))}` |')
    (ROOT / f'docs/migration/{module}.md').write_text('\n'.join(lines)+'\n')
